package com.example.final_project;

import java.util.ArrayList;
import java.util.List;

public class Words {

    List<String> wor_12 = new ArrayList<String>();
    List<String> wor_11 = new ArrayList<String>();
    List<String> wor_10 = new ArrayList<String>();
    List<String> wor_9 = new ArrayList<String>();
    List<String> wor_8 = new ArrayList<String>();
    List<String> wor_7 = new ArrayList<String>();
    List<String> wor_6 = new ArrayList<String>();
    List<String> wor_5 = new ArrayList<String>();
    List<String> wor_4 = new ArrayList<String>();
    List<String> wor_3 = new ArrayList<String>();
    List<String> wor_2 = new ArrayList<String>();
    List<String> fons = new ArrayList<String>();
    List<String> red = new ArrayList<String>();
    List<String> ep = new ArrayList<String>();

    Words(boolean jp){
        fons.add("マチュピク、ペルー");
        fons.add("凱旋門、パリ");
        fons.add("ジュネーブの噴水");
        fons.add("歌う噴水、バルセロナ");
        fons.add("鋳鉄橋、Ironbridge");
        fons.add("デンマーク");
        fons.add("庭園バイザベイ,シンガポール");
        fons.add("アトミウム、ブリュッセル");
        fons.add("ノルウェードゥームズデイボルト");
        fons.add("台北101");
        fons.add("パレ-ロワイヤル,パリ");
        fons.add("キンタダリガレイラ,ポルトガル");
        fons.add("チボリ公園");
        fons.add("モナコの日本庭園");
        fons.add("公園ムアンボラン,タイ");
        fons.add("米国ルート66");
        fons.add("アムステルダム");
        fons.add("プロヴァンス、フランス");
        fons.add("バリ島、インドネシア");
        fons.add("カッパドキア、トルコ");
        fons.add("李の川、中国");
        fons.add("中国-海南島");

        ep.add("幻想");
        ep.add("ひじうにつくしい");

        red.add("こんにちは");
        red.add("パスポート");

        wor_2.add("土地");//земля
        wor_2.add("住民");//жители
        wor_2.add("都市");//города
        wor_2.add("椅子");//стул
        wor_2.add("兄弟");
        wor_2.add("手紙");
        wor_2.add("地域");//регион
        wor_2.add("通訳");
        wor_2.add("社会");//
        wor_2.add("名前");
        wor_2.add("幻想");//фантазия
        wor_2.add("音楽");//музыка
        wor_2.add("明日");
        wor_2.add("中国");
        wor_2.add("住所");//адрес

        wor_3.add("日本語");
        wor_3.add("拡大鏡");//лупа
        wor_3.add("ガラス");
        wor_3.add("ロック");

        wor_4.add("しんこく");
        wor_4.add("ミュート");
        wor_4.add("テキスト");

        wor_5.add("こんにちは");
        wor_5.add("パスポート");

        wor_6.add("はじめまして");
        wor_6.add("ドキュメント");

        wor_7.add("プトレマイオス");
        wor_7.add("マルチスレッド");

        wor_8.add("ひじうにつくしい");
        wor_8.add("ひじうにつくしい");

        wor_12.add("АМПЕРОМЕТРИЯ");
        wor_12.add("РЕВАКЦИНАЦИЯ");

        wor_11.add("АГРОУЧАСТОК");
        wor_11.add("ДРОЖЖЕВАНИЕ");


        wor_10.add("СОЗЕРЦАНИЕ");
        wor_10.add("ГАЗОПРОВОД");


        wor_9.add("АВТОПОЕЗД");
        wor_9.add("ГАСТРОНОМ");


    }

    Words() {
        fons.add("Мачу-Пику, Перу");
        fons.add("Триумфальные ворота, Париж");
        fons.add("Женевский фонтан");
        fons.add("Поющие фонтаны, Барселона");
        fons.add("Чугунный мост, Айронбридж");
        fons.add("Эрсунский мост, Дания");
        fons.add("Сады у залива, Сингапур");
        fons.add("Атомиум, Брюссель");
        fons.add("Хранилище Судного дня, Норвегия");
        fons.add("Тайбэй 101");
        fons.add("Пале-Рояль, Париж");
        fons.add("Кинта да Регайлера, Португалия");
        fons.add("Парк Тиволи, Копенгаген");
        fons.add("Японский сад в Монако");
        fons.add("Парк Муанг-Боран, Таиланд");
        fons.add("Шоссе 66, США");
        fons.add("Амстердам арена");
        fons.add("Прованс, Франция");
        fons.add("Остров Бали, Индонезия");
        fons.add("Каппадоксия, Турция");
        fons.add("Река Ли, Китай");
        fons.add("Остров Хайнань, Китай");

        ep.add("АМПЕРОМЕТРИЯ");
        ep.add("РЕВАКЦИНАЦИЯ");
        ep.add("АГРОУЧАСТОК");
        ep.add("ДРОЖЖЕВАНИЕ");
        ep.add("МАРОДЕРСТВО");
        ep.add("СОЗЕРЦАНИЕ");
        ep.add("ГАЗОПРОВОД");
        ep.add("ФЕРРОСПЛАВ");
        ep.add("АВТОПОЕЗД");
        ep.add("ГАСТРОНОМ");
        ep.add("ДИСПЕРСИЯ");
        ep.add("ИДЕОЛОГИЯ");
        ep.add("КОЛЛЕКТИВ");
        ep.add("МЫ");

        red.add("РУЛЕТ");
        red.add("ПАРАМЕТР");
        red.add("ЛИНЕЙКА");
        red.add("АД");
        red.add("ЛИСТОВКА");
        red.add("КАРАНДАШ");
        red.add("НАУШНИК");
        red.add("ИСЛАМ");
        red.add("СЕРЕБРО");
        red.add("АЛГЕБРА");
        red.add("СТИКЕРЫ");
        red.add("ЛИНЕЙКА");
        red.add("БЛОКНОТ");
        red.add("ФАНТОМ");
        red.add("ПОНЧИК");
        red.add("МАНГАЛ");
        red.add("МАТРАС");
        red.add("МИКРОБ");
        red.add("МЕЧЕТЬ");
        red.add("МЕДУЗА");
        red.add("ЛОББИ");
        red.add("БУТОН");
        red.add("ВИТОК");
        red.add("ВНОВЬ");
        red.add("СНОВА");
        red.add("ВЕТЕР");
        red.add("ЭТИКА");
        red.add("ЭМАЛЬ");
        red.add("ЭЛИТА");

        wor_12.add("АМПЕРОМЕТРИЯ");
        wor_12.add("РЕВАКЦИНАЦИЯ");

        wor_11.add("АГРОУЧАСТОК");
        wor_11.add("ДРОЖЖЕВАНИЕ");
        wor_11.add("МАРОДЕРСТВО");

        wor_10.add("СОЗЕРЦАНИЕ");
        wor_10.add("ГАЗОПРОВОД");
        wor_10.add("ФЕРРОСПЛАВ");

        wor_9.add("АВТОПОЕЗД");
        wor_9.add("ГАСТРОНОМ");
        wor_9.add("ДИСПЕРСИЯ");
        wor_9.add("ИДЕОЛОГИЯ");
        wor_9.add("КОЛЛЕКТИВ");

        wor_8.add("ПАРАМЕТР");
        wor_8.add("ЛИСТОВКА");
        wor_8.add("ЕДИНОРОГ");
        wor_8.add("КАРАНДАШ");

        wor_7.add("НАУШНИК");
        wor_7.add("СЕРЕБРО");
        wor_7.add("АЛГЕБРА");
        wor_7.add("СТИКЕРЫ");
        wor_7.add("ЛИНЕЙКА");
        wor_7.add("БЛОКНОТ");

        wor_6.add("ЙОГУРТ");
        wor_6.add("КАКТУС");
        wor_6.add("МАШИНА");
        wor_6.add("СТАКАН");
        wor_6.add("ЗАВТРА");
        wor_6.add("КЛЕТКА");
        wor_6.add("КУРТКА");
        wor_6.add("АНГИНА");
        wor_6.add("АТЕИЗМ");
        wor_6.add("БРИКЕТ");
        wor_6.add("ВНУЧКА");
        wor_6.add("ГУСЫНЯ");
        wor_6.add("ЕРАЛАШ");
        wor_6.add("ЕРУНДА");
        wor_6.add("ЖЕЛУДЬ");
        wor_6.add("ЗАКЛАД");
        wor_6.add("ЖВАЧКА");
        wor_6.add("ЗНАНИЕ");
        wor_6.add("ИМБИРЬ");
        wor_6.add("ПРЯНИК");
        wor_6.add("ЛУННЫЙ");
        wor_6.add("ЛЕНТЯЙ");
        wor_6.add("ЛЮБОВЬ");
        wor_6.add("МРАМОР");
        wor_6.add("ЛАНДЫШ");
        wor_6.add("МЫШЬЯК");
        wor_6.add("МАССИВ");
        wor_6.add("МАНЕРА");
        wor_6.add("ОРУЖИЕ");
        wor_6.add("ОБОДОК");
        wor_6.add("ПОНЧИК");
        wor_6.add("ПРАВКА");
        wor_6.add("ПАЛУБА");
        wor_6.add("РЕЙДЕР");
        wor_6.add("ФИЗИКА");
        wor_6.add("ПРИБОЙ");
        wor_6.add("РОДИНА");
        wor_6.add("СПИСОК");
        wor_6.add("СТАТУС");
        wor_6.add("СТРЕМЯ");
        wor_6.add("ТАЙНИК");
        wor_6.add("УСЛУГА");
        wor_6.add("УКАЗКА");
        wor_6.add("ФЛАЖОК");
        wor_6.add("ФАНТОМ");
        wor_6.add("ФОРЕЛЬ");
        wor_6.add("ХИРУРГ");
        wor_6.add("ХОЗЯИН");
        wor_6.add("ФАШИЗМ");
        wor_6.add("ФИГУРА");
        wor_6.add("ФЛЕЙТА");
        wor_6.add("ФИГУРА");
        wor_6.add("ШТАНГА");
        wor_6.add("ШЛЕПОК");
        wor_6.add("ЮНОСТЬ");
        wor_6.add("ЮПИТЕР");
        wor_6.add("ЭГОИЗМ");
        wor_6.add("ЭКОЛОГ");
        wor_6.add("ЯНТАРЬ");
        wor_6.add("ЯПОНЦЫ");
        wor_6.add("ЮВЕЛИР");
        wor_6.add("АВГУСТ");
        wor_6.add("АВАРИЯ");
        wor_6.add("АЦЕТОН");
        wor_6.add("АММИАК");
        wor_6.add("АТЕЛЬЕ");
        wor_6.add("АЗИМУТ");
        wor_6.add("АНКЕТА");
        wor_6.add("БУМАГА");
        wor_6.add("БЕНЗОЛ");
        wor_6.add("БЛЮДЦЕ");
        wor_6.add("БАНДИТ");
        wor_6.add("БИБЛИЯ");
        wor_6.add("БОГИНЯ");
        wor_6.add("БИЦЕПС");
        wor_6.add("БАЛАНС");
        wor_6.add("БУЛЬОН");
        wor_6.add("ВЗЯТКА");
        wor_6.add("ВИНТИК");
        wor_6.add("ВЗГЛЯД");
        wor_6.add("ВЕРШОК");
        wor_6.add("ВЕРСТА");
        wor_6.add("ГЕКТАР");
        wor_6.add("ГРАДУС");
        wor_6.add("ГРАФИН");
        wor_6.add("ГРУЗДЬ");
        wor_6.add("ГВОЗДЬ");
        wor_6.add("ГИБРИД");
        wor_6.add("ГАВАНЬ");
        wor_6.add("ГИТАРА");
        wor_6.add("ДЕНЬГИ");
        wor_6.add("ДЕВИЦА");
        wor_6.add("ДЕФЕКТ");
        wor_6.add("ДИПЛОМ");
        wor_6.add("ДОБЫЧА");
        wor_6.add("ДОСТУП");
        wor_6.add("ДИЗЕЛЬ");
        wor_6.add("ЖМУРКИ");
        wor_6.add("ЖУРНАЛ");
        wor_6.add("ЖИТЕЛЬ");
        wor_6.add("ЗАБАВА");
        wor_6.add("ЗАВЕСА");
        wor_6.add("ЗАВХОЗ");
        wor_6.add("ЗАДИРА");
        wor_6.add("ЗАНУДА");
        wor_6.add("ЗАПИСЬ");
        wor_6.add("ЗАПРОС");
        wor_6.add("ЗАРАЗА");
        wor_6.add("ЗАСАДА");
        wor_6.add("ЗАСЕКА");
        wor_6.add("ЗАЩИТА");
        wor_6.add("ЗВАНИЕ");
        wor_6.add("ЗВЕЗДА");
        wor_6.add("ЗДАНИЕ");
        wor_6.add("ЗЕМЛЯК");
        wor_6.add("ЗЕНИЦА");
        wor_6.add("ЗОДИАК");
        wor_6.add("ЗНАЧОК");
        wor_6.add("ИЗОТОП");
        wor_6.add("ИМПОРТ");
        wor_6.add("ИНДИГО");
        wor_6.add("ИРОНИЯ");
        wor_6.add("ИХТИОЛ");
        wor_6.add("КАЗИНО");
        wor_6.add("КАКАДУ");
        wor_6.add("КАКТУС");
        wor_6.add("КАЛИНА");
        wor_6.add("КОЛОШИ");
        wor_6.add("КАМЕНЬ");
        wor_6.add("КАМЕРА");
        wor_6.add("КАМЗОЛ");
        wor_6.add("КАНАВА");
        wor_6.add("КАПЕЛЬ");
        wor_6.add("КАРАУЛ");
        wor_6.add("КАПРОН");
        wor_6.add("КАРБИД");
        wor_6.add("КАРЕТА");
        wor_6.add("КАРНИЗ");
        wor_6.add("КАТЮША");
        wor_6.add("КАССИР");
        wor_6.add("КАФЕЛЬ");
        wor_6.add("КАФТАН");
        wor_6.add("КАЧЕЛИ");
        wor_6.add("МАГНАТ");
        wor_6.add("МАКАКА");
        wor_6.add("МАЛИНА");
        wor_6.add("МАМОНТ");
        wor_6.add("МАНГАЛ");
        wor_6.add("МАТРАС");
        wor_6.add("МИКРОБ");
        wor_6.add("МЕЧЕТЬ");
        wor_6.add("МЕДУЗА");

        wor_5.add("ПАНДА");
        wor_5.add("КОШКА");
        wor_5.add("БЛИНЫ");
        wor_5.add("ДИВАН");
        wor_5.add("АКУЛА");
        wor_5.add("КУКЛА");
        wor_5.add("ПАНДА");
        wor_5.add("УЗОРЫ");
        wor_5.add("ПЕСОК");
        wor_5.add("КНИГА");
        wor_5.add("АКТИВ");
        wor_5.add("ЧАШКА");
        wor_5.add("ТАПОК");
        wor_5.add("АМЕБА");
        wor_5.add("АФЕРА");
        wor_5.add("БУТОН");
        wor_5.add("ВИТОК");
        wor_5.add("ВНОВЬ");
        wor_5.add("СНОВА");
        wor_5.add("ВЕТЕР");
        wor_5.add("ГОЛОД");
        wor_5.add("ГОСТЬ");
        wor_5.add("ГАЙКА");
        wor_5.add("ГУСАР");
        wor_5.add("ГОСТЬ");
        wor_5.add("ЖИЗНЬ");
        wor_5.add("ЖОКЕЙ");
        wor_5.add("ЗАВЕТ");
        wor_5.add("ЗАЙКА");
        wor_5.add("ЖУЧОК");
        wor_5.add("ЗЕРНО");
        wor_5.add("ИСЛАМ");
        wor_5.add("ИКОТА");
        wor_5.add("ИЖИЦА");
        wor_5.add("ИЗЪЯН");
        wor_5.add("КОКОН");
        wor_5.add("КРУИЗ");
        wor_5.add("КАСТА");
        wor_5.add("КИСТЬ");
        wor_5.add("ЛОББИ");
        wor_5.add("ЛЕСТЬ");
        wor_5.add("ЛАКЕЙ");
        wor_5.add("МАСКА");
        wor_5.add("НИМФА");
        wor_5.add("НОСОК");
        wor_5.add("ПЕШКА");
        wor_5.add("ОТСЕК");
        wor_5.add("ОБХОД");
        wor_5.add("ОТЕЛЬ");
        wor_5.add("ОПЕКА");
        wor_5.add("ПЕПЕЛ");
        wor_5.add("ПЛИТА");
        wor_5.add("РОВНО");
        wor_5.add("РУЛЕТ");
        wor_5.add("РУСЛО");
        wor_5.add("РОЯЛЬ");
        wor_5.add("СЪЕЗД");
        wor_5.add("СВЕЧА");
        wor_5.add("СЕВЕР");
        wor_5.add("САРАЙ");
        wor_5.add("ТОЛЩА");
        wor_5.add("ТИПАЖ");
        wor_5.add("УКЛАД");
        wor_5.add("ФАСАД");
        wor_5.add("ЧЕЛКА");
        wor_5.add("ФАКЕЛ");
        wor_5.add("ФИНАЛ");
        wor_5.add("ЧУЖАК");
        wor_5.add("ШАЙБА");
        wor_5.add("ШЕСТЬ");
        wor_5.add("ШТЫРЬ");
        wor_5.add("ШКУРА");
        wor_5.add("ШМЕЛЬ");
        wor_5.add("ЩЕТКА");
        wor_5.add("ЩЕНОК");

        wor_5.add("ЮНКЕР");
        wor_5.add("ЮНОША");
        wor_5.add("ЮРИСТ");
        wor_5.add("ЯРЛЫК");
        wor_5.add("ЯГОДА");
        wor_5.add("ЯКОРЬ");

        wor_4.add("СТУЛ");
        wor_4.add("ЗМЕЯ");
        wor_4.add("ФАКТ");
        wor_4.add("РЕКА");
        wor_4.add("РИТМ");
        wor_4.add("НОТА");
        wor_4.add("ПЯТЬ");
        wor_4.add("ЛИСТ");
        wor_4.add("ЗУБЫ");
        wor_4.add("КЛЕЙ");
        wor_4.add("ЕНОТ");
        wor_4.add("МЫШЬ");
        wor_4.add("НЕБО");
        wor_4.add("ВРАЧ");
        wor_4.add("ЗАЯЦ");
        wor_4.add("ГНОМ");
        wor_4.add("ЯЙЦО");
        wor_4.add("АРФА");
        wor_4.add("ПЛОД");
        wor_4.add("КОРА");
        wor_4.add("ГОРА");
        wor_4.add("НОГА");
        wor_4.add("ПЕРО");
        wor_4.add("МОДА");
        wor_4.add("ВЕРА");
        wor_4.add("КЛЮЧ");
        wor_4.add("ЦВЕТ");
        wor_4.add("ФАЙЛ");
        wor_4.add("СЛОГ");
        wor_4.add("АЖУР");
        wor_4.add("АТОМ");
        wor_4.add("БОРЩ");
        wor_4.add("БУНТ");
        wor_4.add("БЕДА");
        wor_4.add("ГИРЯ");
        wor_4.add("ДЕВА");
        wor_4.add("РЫБА");
        wor_4.add("ДИСК");
        wor_4.add("ДУГА");
        wor_4.add("ЗНАК");
        wor_4.add("ЗЛАК");
        wor_4.add("ЗОНТ");
        wor_4.add("ЗНОЙ");
        wor_4.add("ЗВОН");
        wor_4.add("ИГРА");
        wor_4.add("ИГЛА");
        wor_4.add("ИРИС");
        wor_4.add("ИЗБА");
        wor_4.add("ОЗОН");
        wor_4.add("ПЛЯЖ");
        wor_4.add("НОЧЬ");
        wor_4.add("НИТЬ");
        wor_4.add("ОБЕД");
        wor_4.add("ОЖОГ");
        wor_4.add("ОВАЛ");
        wor_4.add("ВАЗА");
        wor_4.add("ПАРК");
        wor_4.add("СЕМЯ");
        wor_4.add("СЕНО");
        wor_4.add("СТОП");
        wor_4.add("ТЕМП");
        wor_4.add("ЯЩИК");
        wor_4.add("ЯДРО");
        wor_4.add("ЯЗЫК");
        wor_4.add("ЯЩЕР");
        wor_4.add("ЮМОР");
        wor_4.add("ЮБКА");
        wor_4.add("ЮРТА");
        wor_4.add("ШЁЛК");
        wor_4.add("ЩУКА");
        wor_4.add("ЧАРЫ");
        wor_4.add("ЧАСЫ");
        wor_4.add("ЭФИР");
        wor_4.add("ГРУЗ");
        wor_4.add("БАЛЛ");
        wor_4.add("БАРС");
        wor_4.add("ВДОХ");
        wor_4.add("ВЕЩЬ");
        wor_4.add("ВЗОР");
        wor_4.add("ВИНА");
        wor_4.add("ВИЛЫ");
        wor_4.add("ВКУС");
        wor_4.add("ВНУК");
        wor_4.add("ВОДА");
        wor_4.add("ВОЛЯ");
        wor_4.add("СВЕТ");
        wor_4.add("ВРЕД");
        wor_4.add("ВХОД");
        wor_4.add("ВЫСЬ");
        wor_4.add("ЖАБА");
        wor_4.add("ЖАНР");
        wor_4.add("ЖЮРИ");
        wor_4.add("ЗУБР");
        wor_4.add("ЗВОН");
        wor_4.add("КАРА");
        wor_4.add("КОФЕ");
        wor_4.add("КАФЕ");
        wor_4.add("КАША");
        wor_4.add("КВАС");
        wor_4.add("КЕДР");
        wor_4.add("КЕДЫ");
        wor_4.add("КЕКС");
        wor_4.add("КИНО");
        wor_4.add("КЛАД");
        wor_4.add("КЛАН");
        wor_4.add("КЛЕЩ");
        wor_4.add("КЛЮВ");
        wor_4.add("КЛУБ");
        wor_4.add("КЛИЧ");
        wor_4.add("КОНЬ");
        wor_4.add("КРАБ");
        wor_4.add("КРИК");
        wor_4.add("ПЛАН");
        wor_4.add("КРУГ");
        wor_4.add("КУСТ");
        wor_4.add("ЛАПА");
        wor_4.add("ЛАМА");
        wor_4.add("ЛАВА");
        wor_4.add("ЛЖЕЦ");
        wor_4.add("ЛОЖЬ");
        wor_4.add("ЛУПА");
        wor_4.add("ЛЫЖИ");
        wor_4.add("ЛЮДИ");
        wor_4.add("НОША");
        wor_4.add("НЕОН");
        wor_4.add("АЗОТ");
        wor_4.add("НЯНЯ");
        wor_4.add("ОБОД");
        wor_4.add("ОВЦА");
        wor_4.add("ОБОИ");
        wor_4.add("ОКНО");
        wor_4.add("ОПЫТ");
        wor_4.add("КЕДЫ");
        wor_4.add("ДРУГ");
        wor_4.add("ОТЕЦ");
        wor_4.add("ОЧКИ");
        wor_4.add("СЕРП");
        wor_4.add("СМЕХ");
        wor_4.add("СНЕГ");
        wor_4.add("СОВА");
        wor_4.add("СОЮЗ");
        wor_4.add("ЮАНЬ");
        wor_4.add("ЭТАП");
        wor_4.add("СТИХ");
        wor_4.add("СТЫК");
        wor_4.add("ТАНК");
        wor_4.add("УЗЕЛ");
        wor_4.add("ТИШЬ");
        wor_4.add("ТРУД");
        wor_4.add("ТЬМА");

        wor_3.add("СУД");
        wor_3.add("СУД");
        wor_3.add("ЛАК");
        wor_3.add("ЛУК");
        wor_3.add("ЛУГ");
        wor_3.add("НОЖ");
        wor_3.add("ДУБ");
        wor_3.add("ДВА");
        wor_3.add("ТРИ");
        wor_3.add("МЕЛ");
        wor_3.add("САД");
        wor_3.add("ЧИЖ");
        wor_3.add("ВОР");
        wor_3.add("РОТ");
        wor_3.add("ЕЛЬ");
        wor_3.add("БАЛ");
        wor_3.add("ГАЗ");
        wor_3.add("ГУЛ");
        wor_3.add("ДУХ");
        wor_3.add("ДАР");
        wor_3.add("ЕРШ");
        wor_3.add("ЖУК");
        wor_3.add("ИВА");
        wor_3.add("ИМЯ");
        wor_3.add("КУБ");
        wor_3.add("КИТ");
        wor_3.add("ЛОМ");
        wor_3.add("ЛЮК");
        wor_3.add("ОДА");
        wor_3.add("ПИР");
        wor_3.add("МИР");
        wor_3.add("СОМ");
        wor_3.add("СОК");
        wor_3.add("УСЫ");
        wor_3.add("УХА");
        wor_3.add("ФОН");
        wor_3.add("ФЕЯ");
        wor_3.add("ХОД");
        wor_3.add("ЦЕХ");
        wor_3.add("ЧУМ");
        wor_3.add("ШАР");
        wor_3.add("ШУТ");
        wor_3.add("ЮЛА");
        wor_3.add("ЯМА");
        wor_3.add("ТОК");

        wor_2.add("ЁЖ");
        wor_2.add("АД");
        wor_2.add("МЫ");
        wor_2.add("УЖ");
        wor_2.add("ЩИ");
        wor_2.add("ЮГ");
        wor_2.add("ЯР");
        wor_2.add("ЯД");
        wor_2.add("УМ");
        wor_2.add("АС");
        wor_2.add("ВЫ");
    }
}
